version: '3.1'

services:
  app:
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      - ECHO_MODE=debug
    depends_on:
      - redis
    links:
      - redis

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data

volumes:
  redisdata:
